version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "host.docker.internal"  # Access the local database
      DB_USER: root
      DB_PASSWORD: sibi2002
      DB_NAME: RRS
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

volumes:
  db_data:
