# Use a Node base image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy frontend files and install dependencies
COPY rrs_frontend/package*.json ./
RUN npm ci

# Copy the rest of the frontend code
COPY rrs_frontend/ .

# Build the Next.js app
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/out /usr/share/ngix/html

# Expose the Next.js port
EXPOSE 3000

# Start the Next.js app in production mode
CMD ["nginx","-g", "daemon off;"]
